services:
  teaching_assistant:
    - course: "Mathematical Foundations of Artificial Intelligence (MTH701)"
      term: "Fall 2024"
      professor:
        - name: " Prof. Karthik Nandakumar"
          link: "https://scholar.google.com/citations?user=2qx0RnEAAAAJ&hl=en/"
        - name: " Prof. Mingming Gong"
          link: "https://mingming-gong.github.io"
    - course: "Probabilistic and Statistical Inference (ML703)"
      term: "Spring 2025"
      professor:
        - name: " Prof. Tongliang Liu"
          link: "https://tongliang-liu.github.io"
        - name: " Prof. Mingming Gong"
          link: "https://mingming-gong.github.io"
        - name: " Prof. Maxim Panov"
          link: "https://mbzuai.ac.ae/study/faculty/maxim-panov/"
  conference_reviewing:
    - description: ""
  conference_volunteering:
    - role: "Program Volunteer"
      conference: "IEEE International Conference on Data Mining (ICDM)"
      location: "Abu Dhabi"
    - role: "Program Volunteer"
      conference: "The 31st International Conference on Computational Linguistics (COLING)"
      location: "Abu Dhabi"
